title: My Simple Site
description: Welcome to my simple editable website.
hero_image: /images/hero.jpg
features:
  - name: Feature 1
    description: This is the first feature.
  - name: Feature 2
    description: This is the second feature.
  - name: Feature 3
    description: This is the third feature.